CREATE DATABASE IF NOT EXISTS u835525338_IDS_users
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE u835525338_IDS_users;

CREATE TABLE IF NOT EXISTS USR_ROLE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(80) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USR_USER (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(120) NOT NULL UNIQUE,
  EMAIL VARCHAR(180) NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USR_USER_ROLE (
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT fk_app_user_role_user FOREIGN KEY (USER_ID) REFERENCES USR_USER(id),
  CONSTRAINT fk_app_user_role_role FOREIGN KEY (ROLE_ID) REFERENCES USR_ROLE(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_app_user_username ON USR_USER(username);
CREATE INDEX idx_app_role_name ON USR_ROLE(name);
