CREATE DATABASE IF NOT EXISTS u835525338_IDS_main
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE u835525338_IDS_main;

CREATE TABLE IF NOT EXISTS IDS_RISK_LEVEL (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CODE VARCHAR(30) NOT NULL UNIQUE,
  LABEL VARCHAR(80) NOT NULL,
  MIN_CONFIDENCE DECIMAL(5,2) NOT NULL,
  MAX_CONFIDENCE DECIMAL(5,2) NULL,
  SEVERITY_ORDER INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS IDS_ALERT_STATUS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CODE VARCHAR(30) NOT NULL UNIQUE,
  LABEL VARCHAR(80) NOT NULL,
  SORT_ORDER INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS IDS_ALERT (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  EVENT_TIME DATETIME(6) NOT NULL,
  REASON VARCHAR(255) NULL,
  ATTACK VARCHAR(255) NULL,
  CONFIDENCE DECIMAL(5,2) NOT NULL,
  SRC_IP VARCHAR(80) NULL,
  DST_IP VARCHAR(80) NULL,
  SRC_PORT INT NULL,
  DST_PORT INT NULL,
  PROTO INT NULL,
  RISK_LEVEL_ID BIGINT NOT NULL,
  STATUS_ID BIGINT NOT NULL,
  EVENT_HASH VARCHAR(128) NOT NULL UNIQUE,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_IDS_ALERT_RISK
    FOREIGN KEY (RISK_LEVEL_ID)
    REFERENCES IDS_RISK_LEVEL(ID),

  CONSTRAINT FK_IDS_ALERT_STATUS
    FOREIGN KEY (STATUS_ID)
    REFERENCES IDS_ALERT_STATUS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE IDS_ALERT
    ADD COLUMN AI_DETECTED TINYINT(1) NOT NULL DEFAULT 0 AFTER EVENT_HASH,
  ADD COLUMN AI_CONFIDENCE DECIMAL(5,2) NULL AFTER AI_DETECTED,
  ADD COLUMN AI_LABEL VARCHAR(120) NULL AFTER AI_CONFIDENCE,

  ADD COLUMN RULE_DETECTED TINYINT(1) NOT NULL DEFAULT 0 AFTER AI_LABEL,
  ADD COLUMN RULE_ID VARCHAR(120) NULL AFTER RULE_DETECTED,
  ADD COLUMN RULE_CATEGORY VARCHAR(120) NULL AFTER RULE_ID,
  ADD COLUMN RULE_MSG VARCHAR(500) NULL AFTER RULE_CATEGORY,

  ADD COLUMN CORRELATION_KEY VARCHAR(128) NULL AFTER RULE_MSG,
  ADD COLUMN EVIDENCE LONGTEXT NULL AFTER CORRELATION_KEY;

CREATE INDEX IDX_IDS_ALERT_AI_DETECTED
    ON IDS_ALERT(AI_DETECTED, EVENT_TIME DESC);

CREATE INDEX IDX_IDS_ALERT_RULE_DETECTED
    ON IDS_ALERT(RULE_DETECTED, EVENT_TIME DESC);

CREATE INDEX IDX_IDS_ALERT_RULE_ID
    ON IDS_ALERT(RULE_ID);

CREATE INDEX IDX_IDS_ALERT_CORRELATION_KEY
    ON IDS_ALERT(CORRELATION_KEY);

INSERT INTO IDS_RISK_LEVEL (
  CODE,
  LABEL,
  MIN_CONFIDENCE,
  MAX_CONFIDENCE,
  SEVERITY_ORDER
)
VALUES
  ('LOW', 'Low risk', 0.00, 49.99, 1),
  ('MEDIUM', 'Medium risk', 50.00, 79.99, 2),
  ('HIGH', 'High risk', 80.00, NULL, 3)
ON DUPLICATE KEY UPDATE
  LABEL = VALUES(LABEL),
  MIN_CONFIDENCE = VALUES(MIN_CONFIDENCE),
  MAX_CONFIDENCE = VALUES(MAX_CONFIDENCE),
  SEVERITY_ORDER = VALUES(SEVERITY_ORDER);

INSERT INTO IDS_ALERT_STATUS (
  CODE,
  LABEL,
  SORT_ORDER
)
VALUES
  ('NEW', 'New', 1),
  ('VERIFIED', 'Verified', 2),
  ('SAFE', 'Safe', 3)
ON DUPLICATE KEY UPDATE
  LABEL = VALUES(LABEL),
  SORT_ORDER = VALUES(SORT_ORDER);

CREATE INDEX IDX_IDS_ALERT_TIME
  ON IDS_ALERT(EVENT_TIME DESC);

CREATE INDEX IDX_IDS_ALERT_STATUS
  ON IDS_ALERT(STATUS_ID, EVENT_TIME DESC);

CREATE INDEX IDX_IDS_ALERT_RISK
  ON IDS_ALERT(RISK_LEVEL_ID, EVENT_TIME DESC);

CREATE INDEX IDX_IDS_ALERT_SRC_IP
  ON IDS_ALERT(SRC_IP);

CREATE INDEX IDX_IDS_ALERT_DST_IP
  ON IDS_ALERT(DST_IP);

DROP TRIGGER IF EXISTS TRG_IDS_ALERT_BEFORE_INSERT;
DROP TRIGGER IF EXISTS TRG_IDS_ALERT_BEFORE_UPDATE;

DELIMITER $$

CREATE TRIGGER TRG_IDS_ALERT_BEFORE_INSERT
BEFORE INSERT ON IDS_ALERT
FOR EACH ROW
BEGIN
  DECLARE V_RISK_LEVEL_ID BIGINT;
  DECLARE V_STATUS_ID BIGINT;

  IF NEW.STATUS_ID IS NULL THEN
    SELECT ID
    INTO V_STATUS_ID
    FROM IDS_ALERT_STATUS
    WHERE CODE = 'NEW'
    LIMIT 1;

    SET NEW.STATUS_ID = V_STATUS_ID;
  END IF;

  IF NEW.RISK_LEVEL_ID IS NULL THEN
    SELECT ID
    INTO V_RISK_LEVEL_ID
    FROM IDS_RISK_LEVEL
    WHERE NEW.CONFIDENCE >= MIN_CONFIDENCE
      AND (
        MAX_CONFIDENCE IS NULL
        OR NEW.CONFIDENCE <= MAX_CONFIDENCE
      )
    ORDER BY SEVERITY_ORDER DESC
    LIMIT 1;

    SET NEW.RISK_LEVEL_ID = V_RISK_LEVEL_ID;
  END IF;

  IF NEW.EVENT_HASH IS NULL OR NEW.EVENT_HASH = '' THEN
    SET NEW.EVENT_HASH = SHA2(CONCAT_WS('|',
      COALESCE(DATE_FORMAT(NEW.EVENT_TIME, '%Y-%m-%d %H:%i:%s.%f'), ''),
      COALESCE(NEW.REASON, ''),
      COALESCE(NEW.ATTACK, ''),
      COALESCE(CAST(NEW.CONFIDENCE AS CHAR), ''),
      COALESCE(NEW.SRC_IP, ''),
      COALESCE(NEW.DST_IP, ''),
      COALESCE(CAST(NEW.SRC_PORT AS CHAR), ''),
      COALESCE(CAST(NEW.DST_PORT AS CHAR), ''),
      COALESCE(CAST(NEW.PROTO AS CHAR), '')
    ), 256);
  END IF;
END$$

CREATE TRIGGER TRG_IDS_ALERT_BEFORE_UPDATE
BEFORE UPDATE ON IDS_ALERT
FOR EACH ROW
BEGIN
  DECLARE V_RISK_LEVEL_ID BIGINT;

  IF NEW.CONFIDENCE <> OLD.CONFIDENCE THEN
    SELECT ID
    INTO V_RISK_LEVEL_ID
    FROM IDS_RISK_LEVEL
    WHERE NEW.CONFIDENCE >= MIN_CONFIDENCE
      AND (
        MAX_CONFIDENCE IS NULL
        OR NEW.CONFIDENCE <= MAX_CONFIDENCE
      )
    ORDER BY SEVERITY_ORDER DESC
    LIMIT 1;

    SET NEW.RISK_LEVEL_ID = V_RISK_LEVEL_ID;
  END IF;
END$$

DELIMITER ;